FROM ubuntu:22.04

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV CPLUS_INCLUDE_PATH="/usr/include/gdal"
ENV C_INCLUDE_PATH="/usr/include/gdal"

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3.11 python3-pip python3-wheel libpython3.11-dev g++ libgdal-dev cdo python3-dev&& \
    apt-get -y autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


# install packages
RUN python3.11 -m pip install --upgrade pip
# needed to install numpy before gdal
RUN python3.11 -m pip install numpy==2.*
COPY ./requirements-dev.txt /requirements-dev.txt
RUN python3.11 -m pip install -r /requirements-dev.txt

## Ship code
COPY ecodev_cloud/ /app/ecodev_cloud
WORKDIR /app

#Opened ports
#Jupyter
EXPOSE 5000
#Dash or Uvicorn
EXPOSE 80

# Set python path
ENV PYTHONPATH=/app

CMD ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "80"]
